import type { SetupOperation, WorkerJob } from '@taskos/execution-contracts'; import { TestSetupError } from '../errors/worker.errors.js'; import { redactUnknown } from '../evidence/network-collector.js'; import { nowIso } from '../utils/timestamps.js';
function operationUrl(job: WorkerJob, path: string): string { const base = job.target.apiBaseUrl ?? job.target.baseUrl; const url = new URL(path, base); if (url.pathname !== path || url.search || url.hash) throw new TestSetupError(`Unsafe setup path: ${path}`); return url.toString(); }
async function parseJson(response: Response): Promise<unknown> { try { return redactUnknown(await response.json()); } catch (error) { throw new TestSetupError(`Setup endpoint returned invalid JSON (${response.status})`, { cause: error }); } }
export async function executeTestSetup(job: WorkerJob): Promise<SetupOperation[]> {
  const operations: SetupOperation[] = []; const setup = job.testSetup; if (!setup) return operations;
  if (setup.reset) { const startedAt = nowIso(); const url = operationUrl(job, setup.reset.path); const response = await fetch(url, { method: setup.reset.method, headers: { Accept: 'application/json' } }); const body = await parseJson(response); const completedAt = nowIso(); const operation: SetupOperation = { type: 'RESET', method: 'POST', path: setup.reset.path, url, startedAt, completedAt, statusCode: response.status, succeeded: response.ok && typeof body === 'object' && body !== null && (body as Record<string, unknown>).ok === true, response: body }; operations.push(operation); if (!operation.succeeded) throw new TestSetupError(`Demo reset failed with HTTP ${response.status}`); }
  if (setup.configuration) { const startedAt = nowIso(); const url = operationUrl(job, setup.configuration.path); const response = await fetch(url, { method: setup.configuration.method, headers: { Accept: 'application/json', 'Content-Type': 'application/json' }, body: JSON.stringify(setup.configuration.body) }); const body = await parseJson(response); const completedAt = nowIso(); const record = typeof body === 'object' && body !== null ? body as Record<string, unknown> : {}; const succeeded = response.ok && record.duplicateSubmissionBug === setup.configuration.body.duplicateSubmissionBug && record.paymentDelayMs === setup.configuration.body.paymentDelayMs; const operation: SetupOperation = { type: 'CONFIGURATION', method: 'POST', path: setup.configuration.path, url, startedAt, completedAt, statusCode: response.status, succeeded, response: body }; operations.push(operation); if (!succeeded) throw new TestSetupError(`Demo configuration was not applied exactly (HTTP ${response.status})`); }
  return operations;
}
