import { existsSync } from 'node:fs'; import { mkdtemp, readFile } from 'node:fs/promises'; import { createServer } from 'node:http'; import { tmpdir } from 'node:os'; import { join } from 'node:path'; import { chromium } from '@playwright/test'; import { afterEach, describe, expect, it } from 'vitest'; import type { WorkerJob } from '@taskos/execution-contracts'; import { runWorker } from '../../src/runner.js'; import { createTestJob } from '../test-job.js';
describe('local worker execution', () => {
  let closeServer: (() => Promise<void>) | undefined; afterEach(async () => closeServer?.()); const runnable = existsSync(chromium.executablePath()) ? it : it.skip;
  runnable('generates screenshots, trace, logs, manifest, and result JSON', async () => {
    const server = createServer((request, response) => { if (request.url === '/api/payments') { response.setHeader('content-type', 'application/json'); response.end(JSON.stringify({ paymentId: 'payment-1' })); return; } response.setHeader('content-type', 'text/html'); response.end(`<!doctype html><button id="submit">Pay</button><div id="success" hidden>Confirmed</div><script>console.log('fixture-ready');document.querySelector('#submit').addEventListener('click',async()=>{await fetch('/api/payments',{method:'POST'});document.querySelector('#success').hidden=false})</script>`); });
    await new Promise<void>((resolve) => server.listen(0, '127.0.0.1', resolve)); closeServer = () => new Promise<void>((resolve, reject) => server.close((error) => error ? reject(error) : resolve())); const address = server.address(); if (!address || typeof address === 'string') throw new Error('Test server did not bind');
    const outputDirectory = await mkdtemp(join(tmpdir(), 'taskos-worker-')); const base = createTestJob(); const job: WorkerJob = { ...base, target: { baseUrl: `http://127.0.0.1:${address.port}` }, journey: { id: 'local', name: 'Local deterministic checkout', steps: [{ type: 'goto', path: '/' }, { type: 'click', selector: '#submit', name: 'payment-submit', screenshotCheckpoint: true }, { type: 'waitFor', selector: '#success', timeoutMs: 5000 }], successCondition: { type: 'visible', selector: '#success' } }, invariants: [{ id: 'payment', type: 'NO_DUPLICATE_PAYMENT', severity: 'CRITICAL' }], evidence: { ...base.evidence, outputDirectory } };
    const result = await runWorker(job); expect(result.status).toBe('PASSED'); expect(result.metrics.paymentRequestCount).toBe(1); expect(result.evidence.screenshotPaths.length).toBeGreaterThanOrEqual(3);
    for (const path of [join(outputDirectory, 'manifest.json'), join(outputDirectory, 'worker-result.json'), join(outputDirectory, 'trace', 'trace.zip'), join(outputDirectory, 'console', 'console.json'), join(outputDirectory, 'network', 'network.json')]) expect(existsSync(path), path).toBe(true);
    expect(JSON.parse(await readFile(join(outputDirectory, 'manifest.json'), 'utf8'))).toMatchObject({ outcome: 'PASSED', workerId: job.workerId });
  });
});
