import type { Finding, Investigation, Project, WorldConfig } from '@taskos/shared-types'; import type { CreateInvestigationRequest, InvestigationApi } from './investigation-api.js';
const now = () => new Date().toISOString();
const world: WorldConfig = { worldId: 'world-delayed-payment', browser: 'CHROMIUM', viewport: 'DESKTOP', networkProfile: 'SLOW_3G', userProfile: 'IMPATIENT', concurrency: 2, latencyMs: 800, bandwidthKbps: 750, packetLossPercent: 0, offlineDurationMs: 0, inventoryState: { 'demo-sku': 5 }, sessionState: {}, paymentDelayMs: 2200, retryIntervalMs: 300, doubleSubmit: true, webhookOrder: [], injectedFaults: [{ type: 'PAYMENT_DELAY', parameters: { delayMs: 2200 }, startAfterMs: 0, durationMs: null }], randomSeed: 42, reason: 'Explore delayed payment with an impatient user.' };
export class MockInvestigationApi implements InvestigationApi {
  private readonly projects: Project[] = [{ id: 'project-demo', organisationId: 'org-demo', name: 'Demo Store', description: 'A controlled commerce reliability target.', repositoryUrl: null, createdAt: now(), updatedAt: now() }];
  async listProjects() { return this.projects; }
  async createProject(input: { name: string; description: string | null; repositoryUrl: string | null }) { const item = { id: crypto.randomUUID(), organisationId: 'org-demo', ...input, createdAt: now(), updatedAt: now() }; this.projects.push(item); return item; }
  async createInvestigation(input: CreateInvestigationRequest) { return this.investigation(input.name, input.projectId); }
  async getInvestigation(id: string) { return this.investigation(id === 'investigation-demo' ? 'Delayed payments under impatience' : 'Checkout investigation', 'project-demo'); }
  async listFindings(investigationId: string): Promise<Finding[]> { return [{ id: 'finding-duplicate-payment', investigationId, title: 'Duplicate payment after impatient resubmission', summary: 'A second submit during the delayed payment window created two successful payment records for one order.', severity: 'HIGH', confidence: 'CONFIRMED', reproductionCount: 3, causalConditions: { paymentDelayMs: 2200, retryIntervalMs: 300, doubleSubmit: true }, createdAt: now(), updatedAt: now() }]; }
  private investigation(name: string, projectId: string): Investigation { return { id: 'investigation-demo', projectId, environmentId: 'environment-demo', journeyId: 'journey-checkout', scenarioId: 'scenario-delay', name, status: 'REPRODUCING', plan: { objective: 'Find checkout failures caused by delayed payment responses and impatient users.', journeyId: 'journey-checkout', scenarioId: 'scenario-delay', worldPack: 'commerce', selectedVariables: ['paymentDelayMs', 'retryIntervalMs', 'doubleSubmit'], initialWorldCount: 8, maximumWorldCount: 24, maximumConcurrentWorkers: 4, timeoutSeconds: 120, retryCount: 1, safetyConstraints: [], invariants: [], worlds: [world], planningExplanation: 'Sweep payment delay and user retry timing, then reproduce any duplicate charge.', aiProvider: 'MOCK', estimatedComputeUnits: 8 }, aggregateProgress: 78, workerCounts: { queued: 1, running: 2, completed: 8, failed: 1 }, recentEvents: [{ id: 'event-1', type: 'finding_confirmed', occurredAt: now(), data: { findingId: 'finding-duplicate-payment' } }, { id: 'event-2', type: 'reproduction_started', occurredAt: now(), data: { repeats: 3 } }], findingsCount: 1, elapsedTimeSeconds: 94, createdAt: now(), updatedAt: now() }; }
}
