import type { ExperimentPlan, WorldConfig } from '@taskos/shared-types';
import type { AIProvider, CompiledInvariant } from '../../contracts/ai-provider.js';
import type { EvidenceBackedExplanation, EvidenceSummaryRequest, FindingExplanationRequest } from '../../contracts/explanation.types.js';
import type { FollowUpRequest, PlanningRequest } from '../../contracts/planner.types.js';

function world(worldId: string, reason: string, overrides: Partial<WorldConfig> = {}): WorldConfig {
  return { worldId, browser: 'CHROMIUM', viewport: 'DESKTOP', networkProfile: 'NORMAL', userProfile: 'NORMAL', concurrency: 1, latencyMs: 0, bandwidthKbps: null, packetLossPercent: 0, offlineDurationMs: 0, inventoryState: { 'demo-sku': 5 }, sessionState: {}, paymentDelayMs: 0, retryIntervalMs: 0, doubleSubmit: false, webhookOrder: [], injectedFaults: [], randomSeed: 42, reason, ...overrides };
}

export class MockAIProvider implements AIProvider {
  readonly name = 'MOCK' as const;
  async generateExperimentPlan(request: PlanningRequest): Promise<ExperimentPlan> {
    const worlds = [
      world('baseline', 'Establish the healthy checkout baseline.'),
      world('delayed-impatient', 'Exercise delayed payment with an impatient customer.', { userProfile: 'IMPATIENT', networkProfile: 'SLOW_3G', latencyMs: 800, paymentDelayMs: 2000, retryIntervalMs: 300, doubleSubmit: true, injectedFaults: [{ type: 'PAYMENT_DELAY', parameters: { delayMs: 2000 }, startAfterMs: 0, durationMs: null }, { type: 'DOUBLE_SUBMIT', parameters: {}, startAfterMs: 0, durationMs: null }] }),
    ];
    return { objective: request.objective, journeyId: request.journeyId, scenarioId: request.scenarioId, worldPack: request.worldPack, selectedVariables: ['latencyMs', 'paymentDelayMs', 'userProfile', 'doubleSubmit'], initialWorldCount: worlds.length, maximumWorldCount: 20, maximumConcurrentWorkers: 4, timeoutSeconds: 120, retryCount: 1, safetyConstraints: request.safetyConstraints, invariants: [], worlds, planningExplanation: 'Compare a baseline with a delayed, impatient double-submission world; adapt around any reproduced violation.', aiProvider: 'MOCK', estimatedComputeUnits: 2 };
  }
  async compileInvariant(description: string): Promise<CompiledInvariant> { return { name: description.slice(0, 80), assertion: { type: 'custom', description }, explanation: 'Mock compilation; review before execution.' }; }
  async explainFinding(request: FindingExplanationRequest): Promise<EvidenceBackedExplanation> { return { summary: request.title, supportingEvidence: request.evidenceReferences, limitations: ['Generated by the deterministic mock provider.'] }; }
  async generateFollowUpExperiments(request: FollowUpRequest): Promise<WorldConfig[]> { return [world(`${request.failingWorld.worldId}-repeat`, 'Repeat the exact failing world.', request.failingWorld)]; }
  async summariseEvidence(request: EvidenceSummaryRequest): Promise<EvidenceBackedExplanation> { return { summary: request.invariantViolations.join('; ') || 'No invariant violations.', supportingEvidence: request.artifactDescriptions, limitations: [] }; }
}
