import { createRequire } from 'node:module'; import type { Browser, BrowserContext, Page, Video } from '@playwright/test'; import type { EvidenceManifest, InvariantEvaluationResult, SetupOperation, WorkerJob, WorkerResult } from '@taskos/execution-contracts'; import { createBrowserContext } from './browser/browser-context.js'; import { launchBrowser, resolveViewport } from './browser/browser-factory.js'; import { EvidenceCollector, type EvidenceArtifacts } from './evidence/evidence-collector.js'; import { writeEvidenceManifest } from './evidence/evidence-manifest.js'; import { NavigationError, WorkerError, WorkerTimeoutError } from './errors/worker.errors.js'; import { FaultController } from './faults/fault-controller.js'; import { InvariantRegistry } from './invariants/invariant-registry.js'; import type { JourneyExecutionResult } from './journey/journey.types.js'; import { executeJourney } from './journey/journey-executor.js'; import { writeWorkerResult } from './reporting/result-writer.js'; import { buildWorkerResult } from './reporting/worker-result-builder.js'; import { executeTestSetup } from './setup/test-setup-executor.js'; import { ensureDirectory, fileSize, safeChildPath } from './utils/filesystem.js'; import { nowIso } from './utils/timestamps.js';
const playwrightVersion = (createRequire(import.meta.url)('@playwright/test/package.json') as { version: string }).version;
const emptyJourney = (job: WorkerJob): JourneyExecutionResult => ({ completed: false, completedSteps: 0, totalSteps: job.journey.steps.length, actions: [] });
const emptyEvidence = (): EvidenceArtifacts => ({ artifacts: [], screenshotPaths: [], evidenceErrors: [] });
export interface RunWorkerOptions { outputPath?: string; debug?: boolean }
export async function runWorker(job: WorkerJob, options: RunWorkerOptions = {}): Promise<WorkerResult> {
  const startedAt = nowIso(); const outputPath = options.outputPath ?? safeChildPath(job.evidence.outputDirectory, 'worker-result.json'); const manifestPath = safeChildPath(job.evidence.outputDirectory, 'manifest.json'); await ensureDirectory(job.evidence.outputDirectory);
  let browser: Browser | undefined; let browserVersion = 'unavailable'; let context: BrowserContext | undefined; let page: Page | undefined; let evidenceCollector: EvidenceCollector | undefined; let faults: FaultController | undefined; let journey = emptyJourney(job); let evaluations: InvariantEvaluationResult[] = []; let evidence = emptyEvidence(); let setupOperations: SetupOperation[] = []; const media: { video?: Video } = {}; let terminalError: unknown; let forcedStatus: WorkerResult['status'] | undefined;
  const execute = async (): Promise<void> => {
    setupOperations = await executeTestSetup(job); browser = await launchBrowser(job.browser); browserVersion = browser.version(); const resources = await createBrowserContext(browser, job); context = resources.context; page = await context.newPage(); const video = page.video(); if (video) media.video = video; evidenceCollector = new EvidenceCollector(job); faults = new FaultController(context, page, job); await evidenceCollector.start(context, page); await faults.install();
    const initialUrl = job.target.journeyPath ? new URL(job.target.journeyPath, job.target.baseUrl).toString() : job.target.baseUrl; try { await page.goto(initialUrl, { waitUntil: 'domcontentloaded' }); } catch (error) { throw new NavigationError(`Unable to navigate to initial target ${initialUrl}`, { cause: error }); } await evidenceCollector.screenshots.captureInitial(page);
    journey = await executeJourney(page, job, faults, evidenceCollector.screenshots); if (journey.completed) await evidenceCollector.screenshots.captureFinal(page); else await evidenceCollector.screenshots.captureFailure(page);
    await evidenceCollector.network.settle(); evaluations = await new InvariantRegistry().evaluate(job.invariants, { networkEvents: evidenceCollector.network.events, journeyActions: journey.actions, page, job, ...(job.evidence.network ? { networkEvidencePath: safeChildPath(job.evidence.outputDirectory, 'network', 'network.json') } : {}), screenshotPaths: evidenceCollector.screenshots.paths }); evidence = await evidenceCollector.finish(context, page);
  };
  let timer: NodeJS.Timeout | undefined;
  try { await Promise.race([execute(), new Promise<never>((_resolve, reject) => { timer = setTimeout(() => { void browser?.close(); reject(new WorkerTimeoutError(job.limits.timeoutMs)); }, job.limits.timeoutMs); })]); }
  catch (error) { terminalError = error; forcedStatus = error instanceof WorkerTimeoutError ? 'TIMED_OUT' : error instanceof WorkerError && (error.code === 'JOURNEY_STEP_FAILED' || error.code === 'NAVIGATION_FAILED') ? 'FAILED' : 'RUNNER_ERROR'; if (error instanceof NavigationError) journey = { ...journey, failedStep: { index: 0, name: 'initial-navigation', type: 'goto', error: error.message } }; if (page && evidenceCollector) { try { await evidenceCollector.screenshots.captureFailure(page); } catch { /* retain primary error */ } try { if (context) evidence = await evidenceCollector.finish(context, page); } catch { /* collectors are non-fatal */ } } }
  finally { if (timer) clearTimeout(timer); if (context) try { await context.close(); } catch { /* browser close may already have closed context */ } if (media.video) try { const videoPath = await media.video.path(); evidence.videoPath = videoPath; evidence.artifacts.push({ type: 'VIDEO', path: videoPath, mimeType: 'video/webm', sizeBytes: await fileSize(videoPath) }); } catch { /* video is optional evidence */ } if (browser) try { await browser.close(); } catch { /* cleanup is best-effort */ } }
  const completedAt = nowIso(); const error = terminalError ? { code: terminalError instanceof WorkerError ? terminalError.code : 'UNEXPECTED_RUNNER_ERROR', message: terminalError instanceof Error ? terminalError.message : 'Unknown runner error', ...(options.debug && terminalError instanceof Error && terminalError.stack ? { stack: terminalError.stack } : {}) } : undefined;
  const result = buildWorkerResult({ workerId: job.workerId, experimentId: job.experimentId, worldId: job.worldId, startedAt, completedAt, journey, invariantEvaluations: evaluations, networkEvents: evidenceCollector?.network.events ?? [], consoleEvents: evidenceCollector?.console.events ?? [], evidence, manifestPath, appliedFaults: faults?.allAppliedFaults() ?? [], ...(forcedStatus ? { forcedStatus } : {}), ...(error ? { error } : {}) });
  const viewport = resolveViewport(job.browser.viewport); const manifest: EvidenceManifest = { workerId: job.workerId, worldId: job.worldId, experimentId: job.experimentId, startedAt, completedAt, browser: { playwrightVersion, engine: job.browser.engine, version: browserVersion, viewport, headless: job.browser.headless }, world: job.world, randomSeed: job.world.randomSeed, setupOperations, appliedFaults: result.appliedFaults, journeyStepsAttempted: journey.actions, artifacts: [...evidence.artifacts, { type: 'WORKER_RESULT', path: outputPath, mimeType: 'application/json' }], outcome: result.status, ...(error ? { errorSummary: error.message } : {}), evidenceErrors: evidence.evidenceErrors };
  await writeEvidenceManifest(manifestPath, manifest); await writeWorkerResult(outputPath, result); return result;
}
