export const demoProductFixtureIds = {
  organisation: 'organisation_demo_taskos',
  project: 'project_demo_checkout',
  environment: 'environment_demo_local',
  journey: 'journey_checkout',
  scenario: 'scenario_duplicate_submission',
  invariant: 'invariant_single_checkout_submission',
} as const;

export const demoCheckoutJourneySteps = [
  {
    id: 'journey_checkout_step_01',
    order: 0,
    action: 'NAVIGATE',
    selector: null,
    value: '/products/test-product',
    metadata: {},
  },
  {
    id: 'journey_checkout_step_02',
    order: 1,
    action: 'WAIT',
    selector: '[data-testid="product-page"]',
    value: null,
    metadata: {},
  },
  {
    id: 'journey_checkout_step_03',
    order: 2,
    action: 'CLICK',
    selector: '[data-testid="add-to-cart"]',
    value: null,
    metadata: {},
  },
  {
    id: 'journey_checkout_step_04',
    order: 3,
    action: 'CLICK',
    selector: '[data-testid="open-cart"]',
    value: null,
    metadata: {},
  },
  {
    id: 'journey_checkout_step_05',
    order: 4,
    action: 'WAIT',
    selector: '[data-testid="cart-item"]',
    value: null,
    metadata: {},
  },
  {
    id: 'journey_checkout_step_06',
    order: 5,
    action: 'CLICK',
    selector: '[data-testid="checkout-button"]',
    value: null,
    metadata: {},
  },
  {
    id: 'journey_checkout_step_07',
    order: 6,
    action: 'FILL',
    selector: '[data-testid="email-input"]',
    value: 'test@taskos.dev',
    metadata: {},
  },
  {
    id: 'journey_checkout_step_08',
    order: 7,
    action: 'CLICK',
    selector: '[data-testid="pay-button"]',
    value: null,
    metadata: {},
  },
  {
    id: 'journey_checkout_step_09',
    order: 8,
    action: 'WAIT',
    selector: '[data-testid="order-confirmation"]',
    value: null,
    metadata: {},
  },
] as const;
