import type { Page, Request, Response } from '@playwright/test'; import type { NetworkEvent, WorkerJob } from '@taskos/execution-contracts'; import { nowIso } from '../utils/timestamps.js'; import { matchesRequestPattern, orderPatterns, paymentPatterns } from '../faults/network-faults.js'; import { writeJson } from '../utils/filesystem.js';
const SENSITIVE_KEY = /authorization|cookie|set-cookie|x-api-key|password|passwd|secret|token|credential/i;
export function redactHeaders(headers: Record<string, string>): Record<string, string> { return Object.fromEntries(Object.entries(headers).map(([key, value]) => [key, SENSITIVE_KEY.test(key) ? '[REDACTED]' : value])); }
export function redactUnknown(value: unknown): unknown { if (Array.isArray(value)) return value.map(redactUnknown); if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value as Record<string, unknown>).map(([key, item]) => [key, SENSITIVE_KEY.test(key) ? '[REDACTED]' : redactUnknown(item)])); if (typeof value === 'string') return value.replace(/(bearer\s+)[a-z0-9._~+/-]+/gi, '$1[REDACTED]').replace(/((?:password|token|secret|api[_-]?key)\s*[=:]\s*)[^\s,;]+/gi, '$1[REDACTED]'); return value; }
export type CapturedNetworkEvent = NetworkEvent;
export class NetworkCollector {
  readonly events: CapturedNetworkEvent[] = []; private readonly pending = new Map<Request, CapturedNetworkEvent>(); private readonly responseTasks = new Set<Promise<void>>();
  constructor(private readonly job: WorkerJob) {}
  attach(page: Page): void {
    page.on('request', (request) => { const isPaymentRequest = matchesRequestPattern(request.url(), paymentPatterns(this.job)); const isOrderRequest = matchesRequestPattern(request.url(), orderPatterns(this.job)); const selectedRequestFields = isPaymentRequest || isOrderRequest ? this.safeRequestFields(request) : undefined; const correlationKey = this.correlationKey(request, selectedRequestFields); const event: CapturedNetworkEvent = { id: crypto.randomUUID(), url: request.url(), method: request.method(), requestTimestamp: nowIso(), resourceType: request.resourceType(), isPaymentRequest, isOrderRequest, ...(correlationKey ? { correlationKey } : {}), ...(selectedRequestFields && Object.keys(selectedRequestFields).length ? { selectedRequestFields } : {}) }; this.events.push(event); this.pending.set(request, event); });
    page.on('response', (response) => { const task = this.recordResponse(response); this.responseTasks.add(task); void task.finally(() => this.responseTasks.delete(task)); });
    page.on('requestfailed', (request) => { const event = this.pending.get(request); if (!event) return; event.failureReason = request.failure()?.errorText ?? 'Request failed'; this.complete(event); });
  }
  private async recordResponse(response: Response): Promise<void> { const event = this.pending.get(response.request()); if (!event) return; event.statusCode = response.status(); event.responseTimestamp = nowIso(); event.durationMs = new Date(event.responseTimestamp).getTime() - new Date(event.requestTimestamp).getTime(); if (event.isPaymentRequest || event.isOrderRequest) { const contentType = response.headers()['content-type'] ?? ''; if (contentType.includes('application/json')) { try { const selected = this.selectFields(redactUnknown(await response.json()), ['paymentId', 'orderId', 'status', 'idempotencyKey']); if (Object.keys(selected).length) event.selectedResponseFields = selected; } catch { /* response bodies are optional evidence */ } } } this.pending.delete(response.request()); }
  private complete(event: CapturedNetworkEvent): void { event.responseTimestamp = nowIso(); event.durationMs = new Date(event.responseTimestamp).getTime() - new Date(event.requestTimestamp).getTime(); }
  write(path: string): Promise<void> { return writeJson(path, this.events); }
  async settle(): Promise<void> { await Promise.allSettled([...this.responseTasks]); }
  private safeRequestFields(request: Request): Record<string, unknown> { let parsed: unknown; try { parsed = request.postDataJSON(); } catch { parsed = undefined; } return this.selectFields(redactUnknown(parsed), ['cartId', 'amount', 'currency', 'idempotencyKey', 'paymentId']); }
  private selectFields(value: unknown, allowed: string[]): Record<string, unknown> { if (!value || typeof value !== 'object' || Array.isArray(value)) return {}; const record = value as Record<string, unknown>; return Object.fromEntries(allowed.filter((key) => record[key] !== undefined).map((key) => [key, record[key]])); }
  private correlationKey(request: Request, fields: Record<string, unknown> | undefined): string | undefined { for (const key of ['idempotencyKey', 'paymentId']) if (typeof fields?.[key] === 'string') return fields[key] as string; const headers = redactHeaders(request.headers()); for (const key of ['idempotency-key', 'x-idempotency-key']) if (headers[key] && headers[key] !== '[REDACTED]') return headers[key]; return undefined; }
}
