import type { InvariantEvaluationResult } from '@taskos/execution-contracts'; import { matchesRequestPattern, orderPatterns } from '../faults/network-faults.js'; import type { InvariantDefinition, InvariantEvaluationContext, InvariantEvaluator } from './invariant-evaluator.interface.js'; import { configuredMethods, configuredPatterns } from './invariant-evaluator.interface.js';
function extractIdentifier(body: unknown): string | undefined { if (!body || typeof body !== 'object') return undefined; const record = body as Record<string, unknown>; for (const key of ['orderId', 'order_id', 'id']) if (typeof record[key] === 'string') return record[key]; return undefined; }
export class NoDuplicateOrderInvariant implements InvariantEvaluator {
  readonly type = 'NO_DUPLICATE_ORDER' as const;
  async evaluate(invariant: InvariantDefinition, context: InvariantEvaluationContext): Promise<InvariantEvaluationResult> {
    const patterns = configuredPatterns(invariant.config, orderPatterns(context.job)); const methods = configuredMethods(invariant.config); const matching = context.networkEvents.filter((event) => methods.includes(event.method.toUpperCase()) && matchesRequestPattern(event.url, patterns));
    const responseOrderIds = matching.map((event) => extractIdentifier(event.selectedResponseFields)).filter((value): value is string => Boolean(value)); const domSelector = typeof invariant.config?.orderIdSelector === 'string' ? invariant.config.orderIdSelector : undefined; const domOrderIds = domSelector ? await context.page.locator(domSelector).allTextContents() : []; const identifiers = [...new Set([...responseOrderIds, ...domOrderIds.map((value) => value.trim()).filter(Boolean)])];
    const duplicateByNetwork = matching.length > 1; const duplicateByObservation = identifiers.length > 1; const passed = !duplicateByNetwork && !duplicateByObservation; const evidenceReferences = matching.map((event) => `network-event:${event.id}`); if (domSelector) evidenceReferences.push(...context.screenshotPaths);
    return { invariantId: invariant.id, type: this.type, passed, expected: { maximumOrders: 1 }, observed: { orderRequests: matching.length, requestIds: matching.map((event) => event.id), orderIds: identifiers, timestamps: matching.map((event) => event.requestTimestamp), correlations: matching.map((event) => event.correlationKey).filter(Boolean) }, confidence: duplicateByNetwork && duplicateByObservation ? 0.99 : duplicateByNetwork ? 0.94 : 0.88, evidenceReferences, explanation: passed ? 'Observed at most one qualifying order-creation request and one order identifier.' : `Observed ${matching.length} qualifying order-creation requests and ${identifiers.length} distinct order identifiers.` };
  }
}
